# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Bookify' do
    pod 'Parse'
    pod 'AFNetworking'
    pod 'ParseUI'
    pod 'Font-Awesome-Swift'
    pod 'LGSideMenuController'
end

target 'BookifyTests' do

end

target 'BookifyUITests' do

end
