# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Bookify' do
    pod 'Parse'
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'ParseUI'
    pod 'Google-Material-Design-Icons-Swift', '~> 1.0.1'
    pod 'FontAwesome.swift'
    pod 'LGSideMenuController'
end

target 'BookifyTests' do

end

target 'BookifyUITests' do

end
